---
image: rozum/mingw-gcc:latest

stages:
  - build
  - test
  - document
  - deploy

variables:
  APP_PROJECT_ID: "154"
  GITLAB_BASE_URL: "https://dev.rozum.com"

before_script:
  - eval $(ssh-agent)
  - echo "$COMPANY_SRV_SSH_PRIVATE_KEY" | ssh-add -

library_win:
  stage: build
  tags:
    - servo-testbench
  script:
    - make -C c -e OS=win32
    - make -C c -e OS=win64
    - mkdir c/lib
    - mv c/build-win-32bit/libservo_api-32bit.dll c/lib/libservo_api-32bit.dll
    - mv c/build-win-64bit/libservo_api-64bit.dll c/lib/libservo_api-64bit.dll
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - c/lib

update_tools_win:
  stage: build
  tags:
    - servo-testbench
  script:
    - make -C c -e OS=win32
    - make -C c/tools/fw-update-tool -e OS=win32
    - make -C c/tools/cfg-update-tool -e OS=win32
    - mkdir c/utils
    - mv c/tools/fw-update-tool/build-win-32bit/rr-fw-update-32bit.exe c/utils/rr-fw-update-32bit.exe
    - mv c/tools/cfg-update-tool/build-win-32bit/rr-cfg-update-32bit.exe c/utils/rr-cfg-update-32bit.exe
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - c/utils

tutorial_win:
  stage: build
  tags:
    - servo-testbench
  script:
    - make -C c -e OS=win32
    - make -C c/tutorial -e OS=win32
    - mkdir c/examples
    - mv c/tutorial/build-win-32bit/* c/examples
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - c/examples

update_tools_deb:
  image:
    name: ubuntu:xenial
  stage: build
  tags:
    - servo-testbench
  before_script:
    - echo 'Skipping before-script'
  script:
    - apt-get update && apt-get install -y build-essential
    - bin/package-deb.sh ${CI_COMMIT_TAG}
  only:
    - tags
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    paths:
      - build/*.deb

test_tutorial:
  image: rozum/embed-gcc:latest
  tags:
    - servo-testbench
  stage: test
  script:
    - ./bin/build_and_test_tutorials.sh

generate_docs:
  image: rozum/embed-gcc:python3
  stage: document
  tags:
    - servo-testbench
  script:
    - cd c
    - ( cat Doxyfile ; echo "PROJECT_NUMBER=v$(cat ../version)" ) | doxygen -
    - cd latex && make
    - cd .. && cp latex/refman.pdf html/C-Servo-API.pdf
    - mv html docs

    - pip3 install doxypypy

    - cd ../python
    - ( cat Doxyfile ; echo "PROJECT_NUMBER=v$(cat ../version)" ) | doxygen -
    - mv html docs
  artifacts:
    paths:
      - python/docs
      - c/docs
    expire_in: 1 week

deploy_artifacts:
  image: rozum/embed-gcc:latest
  stage: deploy
  tags:
    - servo-testbench
  script:
    - bin/git-tag.sh
    - bin/publish-artifacts.sh
  only:
    - master
  when: manual

deploy_python_master:
  image:
    name: python:3.7-slim-stretch
  stage: deploy
  tags:
    - servo-testbench
  dependencies:
    - library_win
  before_script:
    - echo 'Skipping before-script'
  script:
    - bin/build_and_deploy_python.sh
  when: manual
  only:
    - master

deploy_python_dev:
  image:
    name: rozum/embed-gcc:python3
  stage: deploy
  tags:
    - servo-testbench
  dependencies:
    - library_win
  before_script:
    - echo 'Skipping before-script'
  script:
    - bin/build_and_deploy_python.sh
  when: manual
  except:
    - master

deploy_python_master_pypi:
  image:
    name: python:3.7-slim-stretch
  stage: deploy
  tags:
    - servo-testbench
  dependencies:
    - library_win
  before_script:
    - echo 'Skipping before-script'
  script:
    - bin/deploy_python_pypi.sh
  only:
    - master
  when: manual

deploy_python_master_testpypi:
  image:
    name: python:3.7-slim-stretch
  stage: deploy
  tags:
    - servo-testbench
  dependencies:
    - library_win
  before_script:
    - echo 'Skipping before-script'
  script:
    - bin/deploy_python_testpypi.sh
  only:
    - master
  when: manual

#integration_tests:
#  stage: deploy
#  script:
#    - 'curl --fail --trace-ascii - --request POST --form "token=$CI_JOB_TOKEN" --form ref=dev-c $GITLAB_BASE_URL/api/v4/projects/$APP_PROJECT_ID/trigger/pipeline'
#  only:
#    - master
#    - dev

#integration_tests_on_demand:
#  stage: deploy
#  script:
#    - 'curl --fail --trace-ascii -  --request POST --form "token=$CI_JOB_TOKEN" --form ref=dev-c $GITLAB_BASE_URL/api/v4/projects/$APP_PROJECT_ID/trigger/pipeline'
#  when: manual
#  except:
#    - master
#    - dev

include:
  - local: ci/sonarqube.gitlab-ci.yml
