#
#Verbose mode
#
VERBOSE=no

#
#Colorize ouput
#
COLORIZE=no

#
#Build directory
#
BUILDDIR = build
PYTHONDIR = ../python/rozum/servo
#
#Executable name
#
EXE_NAME = servo_api

#
#Enable binary creation
#
MAKE_BINARY=no

#
#Enable binary creation
#
MAKE_EXECUTABLE=no

#
#Enable shared library creation
#
MAKE_SHARED_LIB=yes

#
#Enable static library creation
#
MAKE_STATIC_LIB=yes

#
#Enable MAP-file creation
#
CREATE_MAP=no

#
#Tool-chain prefix
#
#TCHAIN = 

#
#CPU specific options
#
#MCPU += -mthumb

#
#C language dialect
#
CDIALECT = gnu99

#
#C++ language dialect
#
CPPDIALECT = c++0x

#
#Optimization
#
OPT_LVL = 2

#
#Additional C flags
#
#CFLAGS += 


#
#Additional CPP flags
#
#CPPCFLAGS += -felide-constructors

#
#Additional linker flags
#
#LDFLAGS += 


#
#Additional static libraries
#
#EXT_LIBS += c_nano
#EXT_LIBS += c

#
#Additional non-project object files
#
#EXT_OBJECTS += /usr/lib/arm-none-eabi/newlib/thumb/libc_nano.a


#
#Preprocessor definitions
#
#PPDEFS += 



#
#Include directories
#
INCDIR += .
INCDIR += include
INCDIR += src

#
#C sources
#
C_SOURCES += $(wildcard src/*.c)

#
#Assembler sources
#
#S_SOURCES += 

#
#CPP sources
#
#CPP_SOURCES += 

#
#Linker scripts
#
#LDSCRIPT += 

include core.mk
